"use client";

import React, { useState, useEffect, createContext, useContext, ReactNode } from "react";

type Language = "en" | "ta";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// CLEAN CONSOLIDATED DICTIONARY
const translations: Record<Language, Record<string, string>> = {
  en: {
    "Login to your dashboard": "Login to your dashboard",
    "Track coverage and earnings protection in real-time": "Track coverage and earnings protection in real-time",
    "Join the Parametric Shield": "Join the Parametric Shield",
    "Protect your gig earnings against weather disruptions": "Protect your gig earnings against weather disruptions",
    "Coverage for riders, drivers, and field workers": "Coverage for riders, drivers, and field workers",
    "Live Payout Dashboard": "Live Payout Dashboard",
    "Automatic settlement when rain stops your work": "Automatic settlement when rain stops your work",
    "Worker ID": "Worker ID",
    "Platform Partner": "Platform Partner",
    "Coverage Status": "Coverage Status",
    "Active": "Active",
    "Inactive": "Inactive",
    "Rain Today": "Rain Today",
    "Payout": "Payout",
    "Select your platform": "Select your platform",
    "Uber": "Uber",
    "Zomato": "Zomato",
    "Swiggy" : "Swiggy",
    "Zepto" : "Zepto",
    "Blinkit" : "Blinkit",
    "Porter" : "Porter",
    "Dunzo" : "Dunzo",
    "Ola" : "Ola",
    "Rapido" : "Rapido",
    "Other" : "Other",
    "Enter your platform ID": "Enter your platform ID",
    "Next": "Next",
    "Back": "Back",
    "Confirm": "Confirm",
    "Submit": "Submit",
    "Verified": "Verified",
    "Worker Enrollment": "Worker Enrollment",
    "Get Protected": "Get Protected",
    "Step": "Step",
    "Exit Flow": "Exit Flow",
    "Worker Dashboard": "Worker Dashboard",
    "Active Zone": "Active Zone",
    "Chennai Central · TN-CHE-01": "Chennai Central · TN-CHE-01",
    "Emergency Trigger": "Emergency Trigger",
    "Manually notify of unusual zone disruptions": "Manually notify of unusual zone disruptions",
    "Coverage Map": "Coverage Map",
    "Premium Shield Active": "Premium Shield Active",
    "Next auto-deduction: Apr 11": "Next auto-deduction: Apr 11",
    "Manage Plan": "Manage Plan",
    "Download Certificate": "Download Certificate",
    "History": "History",
    "Zones": "Zones",
    "Settings": "Settings",
    "Active Disruptions": "Active Disruptions",
    "Recent Alerts": "Recent Alerts",
    "Coverage Progress": "Coverage Progress",
    "Payout History": "Payout History",
    "View Details": "View Details",
    "Rain Sensor Hub": "Rain Sensor Hub",
    "Velachery": "Velachery",
    "Pallikaranai": "Pallikaranai",
    "Guindy": "Guindy",
    "Madipakkam": "Madipakkam",
    "Perumbakkam": "Perumbakkam",
    "Semmencherry": "Semmencherry",
    "Sholinganallur": "Sholinganallur",
    "Saidapet": "Saidapet",
    "T. Nagar": "T. Nagar",
    "Kotturpuram": "Kotturpuram",
    "Coverage Zones": "Coverage Zones",
    "Selection (1-3) by Priority": "Selection (1-3) by Priority",
    "Select your primary work zones below": "Select your primary work zones below",
    "Confirm Selection": "Confirm Selection",
    "Aadhaar Number": "Aadhaar Number",
    "Verify OTP": "Verify OTP",
    "Pancard Upload": "Pancard Upload",
    "Verify your PAN details": "Verify your PAN details",
    "Pancard Front View": "Pancard Front View",
    "Position your face in the center of the frame": "Position your face in the center of the frame",
    "Face Verification Enrollment": "Face Verification Enrollment",
    "Face recognition active — AI verification in progress": "Face recognition active — AI verification in progress",
    "Aadhaar e-KYC Verification": "Aadhaar e-KYC Verification",
    "Verification via OTP": "Verification via OTP",
    "12-Digit Aadhaar Number": "12-Digit Aadhaar Number",
    "Policy": "Policy",
    "Parametric Protection": "Parametric Protection",
    "Dynamic Earnings Shield": "Dynamic Earnings Shield",
    "Selected Territory": "Selected Territory",
    "Zones Protected": "Zones Protected",
    "Coverage Window": "Coverage Window",
    "Total Premium": "Total Premium",
    "Premium capped at ₹50 max. Weighted by zone risk profiles.": "Premium capped at ₹50 max. Weighted by zone risk profiles.",
    "Risk Adjusted": "Risk Adjusted",
    "Rainfall Trigger": "Rainfall Trigger",
    "Automatic payouts if rainfall exceeds 5mm/hour in your zone.": "Automatic payouts if rainfall exceeds 5mm/hour in your zone.",
    "Instant Payouts": "Instant Payouts",
    "Money credited to your linked UPI within 15 minutes of the trigger.": "Money credited to your linked UPI within 15 minutes of the trigger.",
    "RideSuraksha uses hyper-local weather data from ISRO satellites. Premium is calculated based on current atmospheric pressure and historical zone volatility.": "RideSuraksha uses hyper-local weather data from ISRO satellites. Premium is calculated based on current atmospheric pressure and historical zone volatility.",
    "Underwriting...": "Underwriting...",
    "Activate Coverage": "Activate Coverage",
    "Day": "Day",
    "Days": "Days",
    "Verification Tier: Bio-Shield ✅": "Verification Tier: Bio-Shield ✅",
    "Vanakkam,": "Vanakkam,",
    "Worker": "Worker",
    "Coverage Active": "Coverage Active",
    "Days Rem.": "Days Rem.",
    "Real-time Zone Disruptions": "Real-time Zone Disruptions",
    "All Zones": "All Zones",
    "Revenue Protection": "Revenue Protection",
    "Total payouts of ₹1,450 secured this month": "Total payouts of ₹1,450 secured this month",
    "Smart Coverage Map": "Smart Coverage Map",
    "Explore high-volatility earning zones": "Explore high-volatility earning zones",
    "Signal Disruption": "Signal Disruption",
    "Manual Override": "Manual Override",
    "Need Help?": "Need Help?",
    "Contact Shield Advisor": "Contact Shield Advisor",
    "Dash": "Dash",
    "Edit Plan": "Edit Plan",
    "Plan Modification": "Plan Modification",
    "Pay +2% Admin Surcharge": "Pay +2% Admin Surcharge",
    "Confirm Changes": "Confirm Changes",
    "Update Coverage": "Update Coverage",
    "Premium Account": "Premium Account",
    "Unlimited Zones": "Unlimited Zones",
    "Upgrade Now": "Upgrade Now",
    "Support": "Support",
    "Help Center": "Help Center",
    "Claims": "Claims",
    "Initiate Claim Terminal": "Initiate Claim Terminal",
    "Upload biometric or situational evidence to trigger parametric protection.": "Upload biometric or situational evidence to trigger parametric protection.",
    "Video Evidence (Required)": "Video Evidence (Required)",
    "Evidence Locked": "Evidence Locked",
    "Drop Evidence Video": "Drop Evidence Video",
    "Maximum 50MB. Support MP4, MOV, WEBM. Hand-held verification preferred.": "Maximum 50MB. Support MP4, MOV, WEBM. Hand-held verification preferred.",
    "Protection Type": "Protection Type",
    "Verification Context": "Verification Context",
    "Auditing Claim...": "Auditing Claim...",
    "Vault Secured": "Vault Secured",
    "Authenticate & Submit": "Authenticate & Submit",
    "By submitting, you agree to AI analysis of your biometric metadata and situational data.": "By submitting, you agree to AI analysis of your biometric metadata and situational data.",
    "History Terminal": "History Terminal",
    "Records": "Records",
    "Processing": "Processing",
    "Settled": "Settled",
    "Declined": "Declined",
    "No historical claim records detected in your partition.": "No historical claim records detected in your partition.",
    "Video Evidence Attached": "Video Evidence Attached",
    "Claim Partition": "Claim Partition",
    "Submission Date": "Submission Date",
    "Requested Value": "Requested Value",
    "Verification Summary": "Verification Summary",
    "Auditor Comments": "Auditor Comments",
    "Close Terminal": "Close Terminal",
    "Protection Claims": "Protection Claims",
    "New Claim": "New Claim",
    "Filing Protocol": "Filing Protocol",
    "Visual Custody": "Visual Custody",
    "Metadata Integrity": "Metadata Integrity",
    "Parametric Trigger": "Parametric Trigger",
    "Priority Support": "Priority Support",
    "Speak to Auditor": "Speak to Auditor",
    "Trust Tier Active": "Trust Tier Active",
    "Bad Air Quality": "Bad Air Quality",
    "Others": "Others"
  },
  ta: {
    "Login to your dashboard": "உங்கள் டேஷ்போர்டில் லாகின் செய்யவும்",
    "Track coverage and earnings protection in real-time": "பாதுகாப்பு மற்றும் வருவாய் பாதுகாப்பை நிகழ்நேரத்தில் கண்காணிக்கவும்",
    "Join the Parametric Shield": "பாராமெட்ரிக் ஷீல்டில் இணையுங்கள்",
    "Protect your gig earnings against weather disruptions": "வானிலை இடையூறுகளுக்கு எதிராக உங்கள் வருவாயைப் பாதுகாக்கவும்",
    "Coverage for riders, drivers, and field workers": "ரெய்டர்கள், ஓட்டுநர்கள் மற்றும் களப்பணியாளர்களுக்கான பாதுகாப்பு",
    "Live Payout Dashboard": "லைவ் பேஅவுட் டேஷ்போர்டு",
    "Automatic settlement when rain stops your work": "மழை உங்கள் வேலையை நிறுத்தும்போது தானியங்கி தீர்வு",
    "Worker ID": "பணியாளர் ஐடி",
    "Platform Partner": "பிளாட்பார்ம் பார்ட்னர்",
    "Coverage Status": "பாதுகாப்பு நிலை",
    "Active": "செயலில் உள்ளது",
    "Inactive": "செயலற்றது",
    "Rain Today": "இன்று மழை",
    "Payout": "பேஅவுட்",
    "Select your platform": "உங்கள் தளத்தைத் தேர்ந்தெடுக்கவும்",
    "Uber": "உபெர்",
    "Zomato": "சொமாட்டோ",
    "Swiggy" : "சுவிக்கி",
    "Zepto" : "செப்டோ",
    "Blinkit" : "பிளிங்கிட்",
    "Porter" : "போர்ட்டர்",
    "Dunzo" : "டன்சோ",
    "Ola" : "ஓலா",
    "Rapido" : "ரேபிடோ",
    "Other" : "மற்றவை",
    "Enter your platform ID": "உங்கள் தள ஐடியை உள்ளிடவும்",
    "Next": "அடுத்து",
    "Back": "பின்புறம்",
    "Confirm": "உறுதிப்படுத்து",
    "Submit": "சமர்ப்பி",
    "Verified": "சரிபார்க்கப்பட்டது",
    "Worker Enrollment": "பணியாளர் பதிவு",
    "Get Protected": "பாதுகாப்பு பெறுங்கள்",
    "Step": "படி",
    "Exit Flow": "வெளியேறு",
    "Worker Dashboard": "பணியாளர் டேஷ்போர்டு",
    "Active Zone": "செயலில் உள்ள மண்டலம்",
    "Chennai Central · TN-CHE-01": "சென்னை சென்ட்ரல் · TN-CHE-01",
    "Emergency Trigger": "அவசரகால தூண்டுதல்",
    "Manually notify of unusual zone disruptions": "வழக்கத்திற்கு மாறான மண்டல இடையூறுகளை கைமுறையாக அறிவிக்கவும்",
    "Coverage Map": "பாதுகாப்பு வரைபடம்",
    "Premium Shield Active": "பிரீமியம் ஷீல்ட் செயலில் உள்ளது",
    "Next auto-deduction: Apr 11": "அடுத்த தானியங்கி கழிப்பு: ஏப் 11",
    "Manage Plan": "திட்டத்தை நிர்வகி",
    "Download Certificate": "சான்றிதழைப் பதிவிறக்கவும்",
    "History": "வரலாறு",
    "Zones": "மண்டலங்கள்",
    "Settings": "அமைப்புகள்",
    "Active Disruptions": "செயலில் உள்ள இடையூறுகள்",
    "Recent Alerts": "சமீபத்திய எச்சரிக்கைகள்",
    "Coverage Progress": "பாதுகாப்பு முன்னேற்றம்",
    "Payout History": "பேஅவுட் வரலாறு",
    "View Details": "விவரங்களைக் காண்க",
    "Rain Sensor Hub": "மழை சென்சார் ஹப்",
    "Velachery": "வேளச்சேரி",
    "Pallikaranai": "பள்ளிக்கரணை",
    "Guindy": "கிண்டி",
    "Madipakkam": "மடிப்பாக்கம்",
    "Perumbakkam": "பெரம்பாக்கம்",
    "Semmencherry": "செம்மஞ்சேரி",
    "Sholinganallur": "சோழிங்கநல்லூர்",
    "Saidapet": "சைதாப்பேட்டை",
    "T. Nagar": "தி. நகர்",
    "Kotturpuram": "கோட்டூர்புரம்",
    "Coverage Zones": "பாதுகாப்பு மண்டலங்கள்",
    "Selection (1-3) by Priority": "முன்னுரிமை அடிப்படையில் தேர்வு (1-3)",
    "Select your primary work zones below": "உங்கள் முதன்மையான பணி மண்டலங்களை கீழே தேர்ந்தெடுக்கவும்",
    "Confirm Selection": "தேர்வை உறுதிப்படுத்தவும்",
    "Aadhaar Number": "ஆதார் எண்",
    "Verify OTP": "OTP-ஐ சரிபார்க்கவும்",
    "Pancard Upload": "பான்கார்டு பதிவேற்றம்",
    "Verify your PAN details": "உங்கள் பான் விவரங்களைச் சரிபார்க்கவும்",
    "Pancard Front View": "பான்கார்டு முன்புறம்",
    "Position your face in the center of the frame": "உங்கள் முகத்தை சட்டத்தின் நடுவில் வைக்கவும்",
    "Face Verification Enrollment": "முக சரிபார்ப்பு பதிவு",
    "Face recognition active — AI verification in progress": "முகத்தை அடையாளம் காணுதல் செயலில் உள்ளது — AI சரிபார்ப்பு நடைபெறுகிறது",
    "Aadhaar e-KYC Verification": "ஆதார் இ-கேஒய்சி சரிபார்ப்பு",
    "Verification via OTP": "OTP வழியாக சரிபார்ப்பு",
    "12-Digit Aadhaar Number": "12 இலக்க ஆதார் எண்",
    "Policy": "கொள்கை",
    "Parametric Protection": "பாராமெட்ரிக் பாதுகாப்பு",
    "Dynamic Earnings Shield": "மாறும் வருமான கேடயம்",
    "Selected Territory": "தேர்ந்தெடுக்கப்பட்ட பகுதி",
    "Zones Protected": "மண்டலங்கள் பாதுகாக்கப்படுகின்றன",
    "Coverage Window": "பாதுகாப்பு காலம்",
    "Total Premium": "மொத்த பிரீமியம்",
    "Premium capped at ₹50 max. Weighted by zone risk profiles.": "பிரீமியம் அதிகபட்சமாக ₹50 ஆக நிர்ணயிக்கப்பட்டுள்ளது. மண்டல அபாயத்தின் அடிப்படையில் கணக்கிடப்படுகிறது.",
    "Risk Adjusted": "அபாயம் சரிசெய்யப்பட்டது",
    "Rainfall Trigger": "மழை பொழிவு தூண்டுதல்",
    "Automatic payouts if rainfall exceeds 5mm/hour in your zone.": "உங்கள் மண்டலத்தில் மழை 5மிமீ/மணிநேரத்திற்கு மேல் பெய்தால் தானியங்கி பேஅவுட்கள்.",
    "Instant Payouts": "தற்போதைய பேஅவுட்கள்",
    "Money credited to your linked UPI within 15 minutes of the trigger.": "தூண்டுதல் ஏற்பட்ட 15 நிமிடங்களுக்குள் உங்கள் இணைக்கப்பட்ட UPI-க்கு பணம் வந்து சேரும்.",
    "RideSuraksha uses hyper-local weather data from ISRO satellites. Premium is calculated based on current atmospheric pressure and historical zone volatility.": "RideSuraksha இஸ்ரோ செயற்கைக்கோள்களின் ஹைப்பர்-லோக்கல் வானிலை தரவைப் பயன்படுத்துகிறது. தற்போதைய வளிமண்டல அழுத்தம் மற்றும் வரலாற்று மண்டல ஏற்ற இறக்கத்தின் அடிப்படையில் பிரீமியம் கணக்கிடப்படுகிறது.",
    "Underwriting...": "மதிப்பிடப்படுகிறது...",
    "Activate Coverage": "பாதுகாப்பை செயல்படுத்து",
    "Day": "நாள்",
    "Days": "நாட்கள்",
    "Verification Tier: Bio-Shield ✅": "சரிபார்ப்பு நிலை: பயோ-ஷீல்ட் ✅",
    "Vanakkam,": "வணக்கம்,",
    "Worker": "பணியாளர்",
    "Coverage Active": "பாதுகாப்பு செயலில் உள்ளது",
    "Days Rem.": "மீதமுள்ள நாட்கள்",
    "Real-time Zone Disruptions": "நிகழ்நேர மண்டல இடையூறுகள்",
    "All Zones": "அனைத்து மண்டலங்கள்",
    "Revenue Protection": "வருவாய் பாதுகாப்பு",
    "Total payouts of ₹1,450 secured this month": "இந்த மாதம் ₹1,450 மொத்த பேஅவுட்கள் பாதுகாக்கப்பட்டுள்ளன",
    "Smart Coverage Map": "ஸ்மார்ட் பாதுகாப்பு வரைபடம்",
    "Explore high-volatility earning zones": "அதிக லாபம் தரக்கூடிய மண்டலங்களை ஆராயுங்கள்",
    "Signal Disruption": "சிக்னல் இடையூறு",
    "Manual Override": "மேனுவல் ஓவர்ரைடு",
    "Need Help?": "உதவி தேவையா?",
    "Contact Shield Advisor": "ஷீல்ட் ஆலோசகரைத் தொடர்பு கொள்ளவும்",
    "Dash": "டேஷ்",
    "Edit Plan": "திட்டத்தைத் திருத்து",
    "Plan Modification": "திட்ட திருத்தம்",
    "Pay +2% Admin Surcharge": "+2% நிர்வாகக் கூடுதல் கட்டணத்தைச் செலுத்தவும்",
    "Confirm Changes": "மாற்றங்களை உறுதிப்படுத்தவும்",
    "Update Coverage": "பாதுகாப்பைப் புதுப்பிக்கவும்",
    "Premium Account": "பிரீமியம் கணக்கு",
    "Unlimited Zones": "வரம்பற்ற மண்டலங்கள்",
    "Upgrade Now": "இப்போது மேம்படுத்தவும்",
    "Support": "ஆதரவு",
    "Help Center": "உதவி மையம்",
    "Claims": "புகார்கள்",
    "Initiate Claim Terminal": "புகார் பதிவு முனையம்",
    "Upload biometric or situational evidence to trigger parametric protection.": "பாதுகாப்பைத் தூண்ட பயோமெட்ரிக் அல்லது சூழ்நிலை ஆதாரங்களைப் பதிவேற்றவும்.",
    "Video Evidence (Required)": "வீடியோ ஆதாரம் (தேவை)",
    "Evidence Locked": "ஆதாரம் பூட்டப்பட்டது",
    "Drop Evidence Video": "ஆதார வீடியோவை இங்கே விடவும்",
    "Maximum 50MB. Support MP4, MOV, WEBM. Hand-held verification preferred.": "அதிகபட்சம் 50MB. MP4, MOV, WEBM ஆதரிக்கப்படுகிறது. வீடியோ சரிபார்ப்பு சிறந்தது.",
    "Protection Type": "பாதுகாப்பு வகை",
    "Verification Context": "சரிபார்ப்பு சூழல்",
    "Auditing Claim...": "புகார் தணிக்கை செய்யப்படுகிறது...",
    "Vault Secured": "பாதுகாக்கப்பட்டது",
    "Authenticate & Submit": "சரிபார்த்து சமர்ப்பிக்கவும்",
    "By submitting, you agree to AI analysis of your biometric metadata and situational data.": "சமர்ப்பிப்பதன் மூலம், உங்கள் தரவுகளின் AI பகுப்பாய்விற்கு ஒப்புக்கொள்கிறீர்கள்.",
    "History Terminal": "வரலாற்று முனையம்",
    "Records": "பதிவுகள்",
    "Processing": "செயலாக்கத்தில்",
    "Settled": "தீர்க்கப்பட்டது",
    "Declined": "நிராகரிக்கப்பட்டது",
    "No historical claim records detected in your partition.": "உங்கள் கணக்கில் வரலாற்றுப் பதிவுகள் எதுவும் இல்லை.",
    "Video Evidence Attached": "வீடியோ ஆதாரம் இணைக்கப்பட்டுள்ளது",
    "Claim Partition": "புகார் எண்",
    "Submission Date": "சமர்ப்பிக்கப்பட்ட தேதி",
    "Requested Value": "கோரப்பட்ட தொகை",
    "Verification Summary": "சரிபார்ப்பு சுருக்கம்",
    "Auditor Comments": "தணிக்கையாளர் கருத்துக்கள்",
    "Close Terminal": "மூடவும்",
    "Protection Claims": "பாதுகாப்பு புகார்கள்",
    "New Claim": "புதிய புகார்",
    "Filing Protocol": "தாக்கல் செய்யும் நெறிமுறை",
    "Visual Custody": "காட்சி ஆதாரம்",
    "Metadata Integrity": "தரவு ஒருமைப்பாடு",
    "Parametric Trigger": "பாராமெட்ரிக் தூண்டுதல்",
    "Priority Support": "முன்னுரிமை ஆதரவு",
    "Speak to Auditor": "தணிக்கையாளரிடம் பேசவும்",
    "Trust Tier Active": "நம்பக நிலை செயலில் உள்ளது",
    "Bad Air Quality": "மோசமான காற்றின் தரம்",
    "Others": "மற்றவை"
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
